### PR TITLE
Guidance about how to run large model training in WML-A 4.7.x

### PR DESCRIPTION
**Pull request by donglinjy**
Provide a simple tutorial to run large model training through wmla rest api.

### CODE REVIEW

**Comment by robin2008** [comment]
Shall we have a tips for FIPS cluster?  just a warn user there might be risk to run in a FIPS environment as the open source packages might not be FIPS compliant.

**Review by robin2008 — APPROVED** [review]
LGTM

**Comment by donglinjy** [comment]
> Shall we have a tips for FIPS cluster? just a warn user there might be risk to run in a FIPS environment as the open source packages might not be FIPS compliant.

@robin2008 done, check it again.

**Comment by robin2008** [comment]
@donglinjy 
Looks good.
and better to have steps to use `dlicmd.py` to submit the same job as an alternative method (Many of the existing customers are using the cli to submit job in WS notebook)

**Comment by donglinjy** [comment]
> @donglinjy Looks good. and better to have steps to use `dlicmd.py` to submit the same job as an alternative method (Many of the existing customers are using the cli to submit job in WS notebook)

That can be next step. I am not sure how many is using `dlicmd.py`, but it is more like something to get start.

**Comment by donglinjy** [comment]
btw, If there is WS notebook, DLE or wml client  or even rest interface is better than `dlicmd.py`. Using command line in notebook should not be encouraged.

**Comment by robin2008** [comment]
Yes, you can revise the guide later, and use `dlicmd.py` in ws notebook (instead of API or python client, there might be still function or experince gaps need to be filled in future) is the real user case in current existing customer.

**Review by robin2008 — APPROVED** [review]
LGTM

**Comment by donglinjy** [comment]
> Yes, you can revise the guide later, and use `dlicmd.py` in ws notebook (instead of API or python client, there might be still function or experince gaps need to be filled in future) is the real user case in current existing customer.

that's okay, I don't doubt there may be people using the `dlicmd.py` in ws notebook. But is it the user choice or anyone showed them to do so? how is user using it in production?

**Pull request merged**
